/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gym.View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;

import Controller.connectDB;
import Gym.Model.LuongNhanVien;
import java.util.List;
import java.util.ArrayList;
import Gym.Controller.ControllerLuongNhanVien;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class frmBangLNV extends javax.swing.JFrame {

    /**
     * Creates new form frmluongnhanvien
     */
    public static Connection conn = null;
    public static PreparedStatement pst = null;
    public static ResultSet rs = null;
    public static Statement stt = null;
    
    LuongNhanVien luongNhanVien = null;
    DefaultTableModel model = null;
    ControllerLuongNhanVien controllerLuongNhanVien = null;
    
    public frmBangLNV() {
        initComponents();
        setLocationRelativeTo(null);
        loadDaTaNhanVien();
        loadCBCV();
        loadCBSearchCVNV();
        this.lbtongnhanvien.setText(" " + this.tbBangLuongNhanVien.getRowCount() + " nhân viên ");
        getSumTongLuong();
    }
    
    public void ProcessAction(boolean a){
         this.btedit.setEnabled(a);
         this.btdelete.setEnabled(a);     
    }
    
    //load data len giao dien
    
     public void loadDaTaNhanVien(){
        model = new DefaultTableModel();
        //set colum cho title - headers
        Vector colum = new Vector();
        colum.add("MaNV");
        colum.add("Ho Ten");
        colum.add("Chuc Vu");
        colum.add("Tu Ngay");
        colum.add("Den Ngay");
        colum.add("Ngay Cong Chuan");
        colum.add("Tong Ngay Cong");
        colum.add("Luong CB");
        colum.add("Luong Chinh");
        colum.add("Luong Phu Cap");
        colum.add("Tong Gio OT");
        colum.add("Luong OT");
        colum.add("Tong Luong");
        colum.add("Ghi Chu");
        //add colum headers vao model
        model.setColumnIdentifiers(colum);
        
        controllerLuongNhanVien = new ControllerLuongNhanVien();
        // set coumn cho data hien thi tren table
        List<LuongNhanVien> listluongNhanVien = controllerLuongNhanVien.getLuongNhanVienFromDB();
        for(int i=0;i<listluongNhanVien.size(); i++){
            
            LuongNhanVien luongNhanVien = (LuongNhanVien)listluongNhanVien.get(i);
            Vector row = new Vector();
            row.add(luongNhanVien.getMaNV());
            row.add(luongNhanVien.getTenNV());
            row.add(luongNhanVien.getChucVu());
            row.add(luongNhanVien.getTuNgay());
            row.add(luongNhanVien.getDenNgay());
            row.add(luongNhanVien.getNgayCongChuan());
            row.add(luongNhanVien.getNgayCongChuan());
            row.add(luongNhanVien.getLuongCoBan());
            row.add(luongNhanVien.getLuongChinh());
            row.add(luongNhanVien.getLuongPhuCap());
            row.add(luongNhanVien.getTongGioTangCa());
            row.add(luongNhanVien.getLuongTangCa());
            row.add(luongNhanVien.getTongLuong());
            row.add(luongNhanVien.getGhiChu());
            
            //add row data vao model
            model.addRow(row);        
        }
        //set model cho table
        this.tbBangLuongNhanVien.setModel(model);
 
    }
     
    public void getSumTongLuong(){
        
        float tongLuong = 0;
        
        for(int i = 0; i< this.tbBangLuongNhanVien.getRowCount(); i++){
            
            tongLuong = tongLuong + Float.parseFloat(this.tbBangLuongNhanVien.getValueAt(i,12).toString());
        }
        
        this.lbtongluongchitra.setText(Float.toString(tongLuong));
    }
    
   
    public void loadCBCV(){

        ArrayList<String> listCB = controllerLuongNhanVien.loadCBCVNhanVien();
        for(String item: listCB){
            this.cbchucvu.addItem(item.toString());
        }
    }

    public void loadCBSearchCVNV(){

        ArrayList<String> listCB = controllerLuongNhanVien.loadCBCVNhanVien();
        for(String item: listCB){
            this.cbsearchchucvu.addItem(item.toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangLuongNhanVien = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JToggleButton();
        cbsearchchucvu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbchucvu = new javax.swing.JComboBox<>();
        datetungay = new com.toedter.calendar.JDateChooser();
        datedenngay = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtngaycongchuan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtluongchinh = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtluongcoban = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txttongngaycong = new javax.swing.JTextField();
        txtMNV = new javax.swing.JTextField();
        txttenNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtluongphucap = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtgiotangca = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txttongluong = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtghichu = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        txttotaltangca = new javax.swing.JTextField();
        btedit = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btrefresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbtongluongchitra = new javax.swing.JLabel();
        lbtongnhanvien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 50));
        setMaximizedBounds(new java.awt.Rectangle(30, 30, 1300, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BẢNG QUẢN LÝ LƯƠNG NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luachon.png"))); // NOI18N
        jLabel2.setText("Lựa chọn");

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/danhsach.png"))); // NOI18N
        jLabel12.setText("Bảng chi tiết nhân viên");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excel.png"))); // NOI18N
        jButton3.setText("Xuất excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Đến ngày");

        jLabel11.setText("Từ ngày");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1500, 700));

        tbBangLuongNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNV", "Họ tên", "Ngày sinh", "Giới tính", "SĐT", "Địa chỉ", "Email", "Ngày vào làm", "Tên TK", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbBangLuongNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBangLuongNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBangLuongNhanVien);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        jLabel4.setText("Tìm kiếm");

        txtsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/timkiem.png"))); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        cbsearchchucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           ---THEO CHỨC VỤ----" }));
        cbsearchchucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsearchchucvuActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã NV");

        jLabel7.setText("Tên NV");

        jLabel8.setText("Chức Vụ");

        jLabel9.setText("Ngày công CT");

        jLabel13.setText("Tổng ngày công");

        jLabel14.setText("Lương cơ bản");

        jLabel15.setText("Lương chính");

        jLabel3.setText("Lương phụ cấp");

        jLabel16.setText("Tổng giờ OT");

        jLabel17.setText("Tổng lương");

        jLabel18.setText("Ghi chú");

        txtghichu.setColumns(20);
        txtghichu.setRows(5);
        jScrollPane3.setViewportView(txtghichu);

        jLabel19.setText("Tổng lương OT");

        btedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        btedit.setText("Sửa");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btdelete.setText("Xóa");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        btrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/process.png"))); // NOI18N
        btrefresh.setText("Làm mới");
        btrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrefreshActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Tổng nhân viên :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("Tổng lương :");

        lbtongluongchitra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtongluongchitra.setForeground(new java.awt.Color(0, 51, 255));
        lbtongluongchitra.setText("Tổng lương");

        lbtongnhanvien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtongnhanvien.setForeground(new java.awt.Color(0, 51, 255));
        lbtongnhanvien.setText("Tổng nhân viên");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btrefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbsearchchucvu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(47, 47, 47)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txttenNV)
                                                    .addComponent(cbchucvu, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel17)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(txttongluong, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txttongngaycong))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(18, 18, 18))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel11))
                                                        .addGap(38, 38, 38)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtngaycongchuan)
                                                    .addComponent(datedenngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(datetungay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtluongcoban)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                    .addComponent(txtluongchinh)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtluongphucap)
                                                    .addComponent(txtgiotangca))))
                                        .addGap(48, 48, 48))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel20))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttotaltangca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbtongluongchitra)
                                            .addComponent(lbtongnhanvien))))))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(txtngaycongchuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtluongphucap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datetungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datedenngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(32, 32, 32)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(txttongluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbsearchchucvu)
                                                .addGap(4, 4, 4))))
                                    .addComponent(jButton3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txttongngaycong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtluongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txttotaltangca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtluongchinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(60, 60, 60)
                                .addComponent(txtgiotangca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbtongnhanvien))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(lbtongluongchitra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btedit)
                        .addGap(18, 18, 18)
                        .addComponent(btdelete)
                        .addGap(18, 18, 18)
                        .addComponent(btrefresh)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBangLuongNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBangLuongNhanVienMouseClicked
        // hiển thị lên text field
        
        ProcessAction(true);
           int row = this.tbBangLuongNhanVien.getSelectedRow();
              
            try{
                if(row != -1 ){
                this.txtMNV.setText(tbBangLuongNhanVien.getValueAt(row,0).toString());
                this.txttenNV.setText(tbBangLuongNhanVien.getValueAt(row,1).toString());
                this.cbchucvu.setSelectedItem(tbBangLuongNhanVien.getValueAt(row,2).toString());
                this.txttongluong.setText(tbBangLuongNhanVien.getValueAt(row,12).toString());
                
                try
                {       
                        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tbBangLuongNhanVien.getValueAt(row,3).toString());
                        this.datetungay.setDate(date);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }  
                
                try
                {       
                        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tbBangLuongNhanVien.getValueAt(row,4).toString());
                        this.datedenngay.setDate(date);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                
                this.txtngaycongchuan.setText(tbBangLuongNhanVien.getValueAt(row,5).toString());
                this.txtluongchinh.setText(tbBangLuongNhanVien.getValueAt(row,8).toString());
                this.txtluongcoban.setText(tbBangLuongNhanVien.getValueAt(row,7).toString());
                this.txttongngaycong.setText(tbBangLuongNhanVien.getValueAt(row,6).toString());
                this.txtluongphucap.setText(tbBangLuongNhanVien.getValueAt(row,9).toString());
                this.txtgiotangca.setText(tbBangLuongNhanVien.getValueAt(row,10).toString());
                this.txttotaltangca.setText(tbBangLuongNhanVien.getValueAt(row,11).toString());
                this.txtghichu.setText(tbBangLuongNhanVien.getValueAt(row,13).toString());     

            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbBangLuongNhanVienMouseClicked

    public void exportExcel_TH(JTable table) {
        JFileChooser chooser = new JFileChooser();
        int i = chooser.showSaveDialog(chooser);
        if (i == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                FileWriter out = new FileWriter(file + ".xls");
                BufferedWriter bwrite = new BufferedWriter(out);
                model = (DefaultTableModel) table.getModel();
                // ten Cot
                for (int j = 0; j < table.getColumnCount(); j++) {
                    bwrite.write(model.getColumnName(j) + "\t");
                }
                bwrite.write("\n");
                // Lay du lieu dong
                for (int j = 0; j < table.getRowCount(); j++) {
                    for (int k = 0; k < table.getColumnCount(); k++) {
                        bwrite.write(model.getValueAt(j, k) + "\t");
                    }
                    bwrite.write("\n");
                }
                bwrite.close();
                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
            }
        }
    }    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // xuất excel
        exportExcel_TH(tbBangLuongNhanVien);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void refresh(){
           
        this.txtMNV.setText("");
        this.txttenNV.setText("");
        this.cbchucvu.setSelectedItem(null);
        this.cbsearchchucvu.setSelectedItem(null);
        
        java.util.Date date = new java.util.Date();
        this.datetungay.setDate(date);
        this.datedenngay.setDate(date);
        
        this.txtngaycongchuan.setText("");
        this.txttongngaycong.setText("");
        this.txtluongcoban.setText("");
        
        this.txttotaltangca.setText("");
        this.txtluongchinh.setText("");
        this.txtluongphucap.setText("");
        this.txtgiotangca.setText("");
        this.txtgiotangca.setText("");
        this.txttongluong.setText("");
        this.txtghichu.setText("");

       }
    private void btrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrefreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btrefreshActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // Edit lương nhân viên
        
                this.txtMNV.setEnabled(false);
        this.txttenNV.setEnabled(false);
        this.cbchucvu.setEnabled(false);

        if(this.txtngaycongchuan.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Ngày công chuẩn không được bỏ trống","Thông báo",2);
                this.txtngaycongchuan.requestFocus();
                return;
        }
        
        if(this.txtngaycongchuan.getText().length()<0)
        {
                JOptionPane.showMessageDialog(null,"Mục ngày công chuẩn không được là số âm","Thông báo",2);
                this.txtngaycongchuan.requestFocus();
                return;
        }
        
//        Pattern patter7 = Pattern.compile("^[0-9]*$");
//        Matcher matche7 = patter7.matcher(this.txtngaycongchuan.getText());
//        if (!matche7.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục ngày công chuẩn không phải là số!");
//                    this.txtngaycongchuan.requestFocus();
//                    return;
//        }
        
        if(this.txttongngaycong.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Tổng ngày công không được bỏ trống","Thông báo",2);
                this.txttongngaycong.requestFocus();
                return;
        }
        
        if(this.txttongngaycong.getText().length()<0)
        {
                JOptionPane.showMessageDialog(null,"Mục ngày tổng ngày công không được là số âm","Thông báo",2);
                this.txttongngaycong.requestFocus();
                return;
        }
                
//        Pattern patter6 = Pattern.compile("^[0-9]*$");
//        Matcher matche6 = patter6.matcher(this.txttongngaycong.getText());
//        if (!matche6.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục tổng ngày công không phải là số!");
//                    this.txttongngaycong.requestFocus();
//                    return;
//        }
        
        if(this.txtluongcoban.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Mục lương cơ bản không được bỏ trống","Thông báo",2);
                this.txtluongcoban.requestFocus();
                return;
        }
        
        if(this.txtluongcoban.getText().length()<0)
        {
                JOptionPane.showMessageDialog(null,"Mục lương cơ bản không được là số âm","Thông báo",2);
                this.txtluongcoban.requestFocus();
                return;
        }
        
        
//        Pattern patter5 = Pattern.compile("^[0-9]*$");
//        Matcher matche5 = patter5.matcher(this.txtluongcoban.getText());
//        if (!matche5.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục lương cơ bản không phải là số!");
//                    this.txtluongcoban.requestFocus();
//                    return;
//        }
        
        if(this.txtluongchinh.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Mục lương chính không được bỏ trống","Thông báo",2);
                this.txtluongchinh.requestFocus();
                return;
        }
        
        if(this.txtluongchinh.getText().length()<0)
        {
                JOptionPane.showMessageDialog(null,"Mục lương chính không được là số âm","Thông báo",2);
                this.txtluongchinh.requestFocus();
                return;
        }
        
//        Pattern patter4 = Pattern.compile("^[0-9]*$");
//        Matcher matche4 = patter4.matcher(this.txtluongchinh.getText());
//        if (!matche4.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục lương chính không phải là số!");
//                    this.txtluongchinh.requestFocus();
//                    return;
//        }
        
        if(this.txtluongphucap.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Mục lương phụ cấp không được bỏ trống","Thông báo",2);
                this.txtluongphucap.requestFocus();
                return;
        }

                
        if(this.txtluongphucap.getText().length()<0)
        {
                JOptionPane.showMessageDialog(null,"Mục lương phụ cấp không được là số âm","Thông báo",2);
                this.txtluongphucap.requestFocus();
                return;
        }
        
//        Pattern patter3 = Pattern.compile("^[0-9]*$");
//        Matcher matche3 = patter3.matcher(this.txtluongphucap.getText());
//        if (!matche3.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục lương phụ cấp không phải là số!");
//                    this.txtluongphucap.requestFocus();
//                    return;
//        }
        
        if(this.txtgiotangca.getText().length()<0)
        {
                JOptionPane.showMessageDialog(null,"Mục giờ tăng ca không được là số âm","Thông báo",2);
                this.txtgiotangca.requestFocus();
                return;
        }
//        
//        Pattern pattern = Pattern.compile("^[0-9]*$");
//        Matcher matcher = pattern.matcher(this.txtgiotangca.getText());
//        if (!matcher.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục giờ tăng ca không phải là số!");
//                    this.txtgiotangca.requestFocus();
//                    return;
//        }
        
        if(this.txttotaltangca.getText().length()<0)
        {
                JOptionPane.showMessageDialog(null,"Mục tổng lương tăng ca không được là số âm","Thông báo",2);
                this.txttotaltangca.requestFocus();
                return;
        }
        
//        Pattern pattern1 = Pattern.compile("^[0-9]*$");
//        Matcher matcher1 = pattern1.matcher(this.txttotaltangca.getText());
//        if (!matcher1.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục tổng lương tăng ca không phải là số!");
//                    this.txttotaltangca.requestFocus();
//                    return;
//        }
        
        if(this.txttongluong.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Mục lương tổng lương không được bỏ trống","Thông báo",2);
                this.txttongluong.requestFocus();
                return;
        }
        
//        Pattern pattern2 = Pattern.compile("^[0-9]*$");
//        Matcher matcher2 = pattern2.matcher(this.txttongluong.getText());
//        if (!matcher2.matches()) {
//                    JOptionPane.showMessageDialog(null, "kí tự tại mục tổng lương không phải là số!");
//                    this.txttongluong.requestFocus();
//                    return;
//        }
        
        luongNhanVien = new LuongNhanVien();
        
        luongNhanVien.setMaNV(this.txtMNV.getText());
        luongNhanVien.setTenNV(this.txttenNV.getText());
        luongNhanVien.setChucVu((String) this.cbchucvu.getSelectedItem());
        
        luongNhanVien.setTuNgay(this.datetungay.getDate());
        luongNhanVien.setDenNgay(this.datedenngay.getDate());
        
        luongNhanVien.setNgayCongChuan(Integer.parseInt(this.txtngaycongchuan.getText()));
        luongNhanVien.setTongNgayCong(Integer.parseInt(this.txttongngaycong.getText()));
        
        luongNhanVien.setLuongCoBan(Float.parseFloat(this.txtluongcoban.getText()));
        luongNhanVien.setLuongChinh(Float.parseFloat(this.txtluongchinh.getText()));
        luongNhanVien.setLuongPhuCap(Float.parseFloat(this.txtluongphucap.getText()));
        luongNhanVien.setTongGioTangCa(Float.parseFloat(this.txtgiotangca.getText()));
        luongNhanVien.setLuongTangCa(Float.parseFloat(this.txttotaltangca.getText()));
        
        String a = this.txtluongchinh.getText();
        String b = this.txtluongphucap.getText();
        String c = this.txttotaltangca.getText();
        String d = this.txttongluong.getText();
        
        int a1 = Integer.parseInt(a);
        int b1 = Integer.parseInt(b);
        int c1 = Integer.parseInt(c);
        int d1 = Integer.parseInt(d);
        
        d1 = a1 + b1 + c1;
        
        String d2 = Integer.toString(d1);
        
        luongNhanVien.setTongLuong(Float.parseFloat(d2));

        luongNhanVien.setGhiChu(this.txtghichu.getText());
        
        controllerLuongNhanVien = new ControllerLuongNhanVien();
        boolean kq =  controllerLuongNhanVien.upDateLuongNhanVien(luongNhanVien);
        if(kq){
            JOptionPane.showMessageDialog(null, "Sửa bảng lương của nhân viên " + this.txttenNV.getText() + " thành công","Thông báo",1);
            DefaultTableModel model = (DefaultTableModel)tbBangLuongNhanVien.getModel();
            model.setRowCount(0);
            loadDaTaNhanVien();           
        }else
        {
            JOptionPane.showMessageDialog(null, "Sửa thất bại","Thông báo",2);
        }
    }//GEN-LAST:event_bteditActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // Xóa bảng lương nhân viên
        
        if(this.txtMNV.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Bạn cần chọn mã nhân viên để xóa","Thông báo",2);
        else
        {   
            int confirmdelete = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa bảng lương của nhân viên " + this.txttenNV.getText() + " này không ?"," Thông báo ",JOptionPane.YES_NO_OPTION);
            if (confirmdelete == JOptionPane.YES_NO_OPTION){
                boolean kq = controllerLuongNhanVien.deleteLuongNhanVien(this.txtMNV.getText());
                if(kq){
                    JOptionPane.showMessageDialog(null,"Bạn đã xóa thành công","Thông báo",1);
                    DefaultTableModel model = (DefaultTableModel)tbBangLuongNhanVien.getModel();
                    model.setRowCount(0);
                    loadDaTaNhanVien();
                    ProcessAction(false);
                    refresh();
                }else{
                    JOptionPane.showMessageDialog(null,"Xóa thất bại !","Thông báo",2);
                }
            }        
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    public void findKhachHangTheoChuvVu(String chucVu){
        
        String sql = "SELECT * FROM LUONGNHANVIEN where ChucVu like ?";
        
        try
        {
            conn = connectDB.connectSQLServer();
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" +chucVu+ "%");
            rs = pst.executeQuery();
            
            while(model.getRowCount()>0){
                model.removeRow(0);
            }

            while(rs.next()){
                
                luongNhanVien = new LuongNhanVien();

                    luongNhanVien.setMaNV(rs.getString("MaNV"));
                    luongNhanVien.setTenNV(rs.getString("Hoten"));
                    luongNhanVien.setChucVu(rs.getString("ChucVu"));
                    luongNhanVien.setTuNgay(rs.getDate("Tungay"));
                    luongNhanVien.setDenNgay(rs.getDate("Denngay"));
                    luongNhanVien.setNgayCongChuan(rs.getInt("Ngaycongchuan"));
                    luongNhanVien.setTongNgayCong(rs.getInt("Tongngaycong"));
                    luongNhanVien.setLuongCoBan(rs.getFloat("Luongcoban"));
                    luongNhanVien.setLuongChinh(rs.getFloat("LuongChinh"));
                    luongNhanVien.setLuongPhuCap(rs.getFloat("Luongphucap"));
                    luongNhanVien.setTongGioTangCa(rs.getFloat("Tonggiotangca"));
                    luongNhanVien.setLuongTangCa(rs.getFloat("Luongtangca"));
                    luongNhanVien.setTongLuong(rs.getFloat("Tongluong"));
                    luongNhanVien.setGhiChu(rs.getString("Ghichu"));
                    
                Vector row = new Vector();
                
                    row.add(luongNhanVien.getMaNV());
                    row.add(luongNhanVien.getTenNV());
                    row.add(luongNhanVien.getChucVu());
                    row.add(luongNhanVien.getTuNgay());
                    row.add(luongNhanVien.getDenNgay());
                    row.add(luongNhanVien.getNgayCongChuan());
                    row.add(luongNhanVien.getNgayCongChuan());
                    row.add(luongNhanVien.getLuongCoBan());
                    row.add(luongNhanVien.getLuongChinh());
                    row.add(luongNhanVien.getLuongPhuCap());
                    row.add(luongNhanVien.getTongGioTangCa());
                    row.add(luongNhanVien.getLuongTangCa());
                    row.add(luongNhanVien.getTongLuong());
                    row.add(luongNhanVien.getGhiChu());

                model.addRow(row);
                 
            }
            this.tbBangLuongNhanVien.setModel(model);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    
    private void cbsearchchucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsearchchucvuActionPerformed

        
    }//GEN-LAST:event_cbsearchchucvuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // tra ve home
        
        loadDaTaNhanVien();
        this.lbtongnhanvien.setText(" " + this.tbBangLuongNhanVien.getRowCount() + " nhân viên ");
        getSumTongLuong();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
                // search thông tin nhân viên
        
        if(this.cbsearchchucvu.getSelectedItem()==null)
        {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn giá trị cần tìm kiếm !","Thông báo",2);
            this.cbsearchchucvu.requestFocus();
            return;
        }

        if(this.cbsearchchucvu.getSelectedItem()!=null)
        {
            findKhachHangTheoChuvVu((String) this.cbsearchchucvu.getSelectedItem());
            this.lbtongnhanvien.setText(""+this.tbBangLuongNhanVien.getRowCount()+" nhân viên ");
            getSumTongLuong();
            return;
        }
    }//GEN-LAST:event_txtsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBangLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBangLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBangLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBangLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBangLNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btrefresh;
    private javax.swing.JComboBox<String> cbchucvu;
    private javax.swing.JComboBox<String> cbsearchchucvu;
    private com.toedter.calendar.JDateChooser datedenngay;
    private com.toedter.calendar.JDateChooser datetungay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbtongluongchitra;
    private javax.swing.JLabel lbtongnhanvien;
    private javax.swing.JTable tbBangLuongNhanVien;
    private javax.swing.JTextField txtMNV;
    private javax.swing.JTextArea txtghichu;
    private javax.swing.JTextField txtgiotangca;
    private javax.swing.JTextField txtluongchinh;
    private javax.swing.JTextField txtluongcoban;
    private javax.swing.JTextField txtluongphucap;
    private javax.swing.JTextField txtngaycongchuan;
    private javax.swing.JToggleButton txtsearch;
    private javax.swing.JTextField txttenNV;
    private javax.swing.JTextField txttongluong;
    private javax.swing.JTextField txttongngaycong;
    private javax.swing.JTextField txttotaltangca;
    // End of variables declaration//GEN-END:variables
}
