/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gym.View;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import Gym.Model.ThongTinSanPham;
import Gym.Model.BanSanPham;
import Gym.Controller.ControllerBanSanPham;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import Gym.Model.SanPham;
import Controller.connectDB;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import Controller.connectDB;
/**
 *
 * @author Admin
 */
public class frmbansanpham extends javax.swing.JFrame {

    /**
     * Creates new form frmbansanpham
     */
    ControllerBanSanPham controllerBanSanPham = new ControllerBanSanPham();
    public static Connection conn = null;
    public static PreparedStatement pst = null;
    public static ResultSet rs = null;
    public static Statement stt = null;
    DefaultTableModel model;
    SanPham sanPham = null;
    public frmbansanpham() {
        initComponents();
        setLocationRelativeTo(null);
        loadDaTaSanPham();
        loadCBDMSP();
        loadCBTENSP();
        loadCBNPPSP();

    }
    
    public void loadDaTaSanPham(){
        model = new DefaultTableModel();
        //set colum cho title - headers
        Vector colum = new Vector();
        colum.add("Mã SP");
        colum.add("Mã DM");
        colum.add("Tên SP");
        colum.add("Số Lượng");
        colum.add("Đơn Giá");
        colum.add("Mã NPPSP");
        colum.add("T.Gian Nhận");
        colum.add("Ghi Chú");
        colum.add("Tổng Giá");
        
        //add colum headers vao model
        model.setColumnIdentifiers(colum);
        
        // set coumn cho data hien thi tren table
        List<SanPham> listSanPham = controllerBanSanPham.getSanPhamFromDB();
        for(int i=0;i<listSanPham.size(); i++){
            
            SanPham sanPham = (SanPham)listSanPham.get(i);
            Vector row = new Vector();
            row.add(sanPham.getMaSP());
            row.add(sanPham.getMaDM());
            row.add(sanPham.getTenSP());
            row.add(sanPham.getSoLuong());
            row.add(sanPham.getDonGia());
            row.add(sanPham.getMaNPPSP());
            row.add(sanPham.getThoiGianNhan());
            row.add(sanPham.getGhiChu());
            row.add(sanPham.getTongGia());
            
            //add row data vao model
            model.addRow(row);        
        }
        //set model cho table
        this.tbbansanpham.setModel(model);
        this.lbtongso.setText("Có " +this.tbbansanpham.getRowCount()+ " sản phẩm");
    }
    
    public void loadCBDMSP(){
               
        ArrayList<String> listCBDMSP = controllerBanSanPham.loadCBDMSP();
        for(String item: listCBDMSP){
            this.cbMaDMSP.addItem(item.toString());
        }
    }
    public void loadCBTENSP(){
               
        ArrayList<String> listCBTSP = controllerBanSanPham.loadCBTENSP();
        for(String item: listCBTSP){
            this.cbTenSP.addItem(item.toString());
        }
    }
    
    public void loadCBNPPSP(){
        
        ArrayList<String> listCBNPPSP = controllerBanSanPham.loadCBNPSP();
        for(String item : listCBNPPSP){
            
            this.cbNPPSP.addItem(item);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbMaDMSP = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbTenSP = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        txtgiaban = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btrefresh = new javax.swing.JButton();
        btBan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btsearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datengayban = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdongia = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbbansanpham = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txttonggia = new javax.swing.JTextField();
        cethanhtoan = new javax.swing.JCheckBox();
        ceconno = new javax.swing.JCheckBox();
        txtsearchtenSP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lbtongso = new javax.swing.JLabel();
        bthome = new javax.swing.JButton();
        cbNPPSP = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bán sản phẩm");
        setLocation(new java.awt.Point(80, 30));
        setMaximizedBounds(new java.awt.Rectangle(50, 20, 1000, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("TRANG BÁN SẢN PHẨM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luachon.png"))); // NOI18N
        jLabel2.setText("Lựa chọn");

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        cbMaDMSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "     -- DANH MỤC SẢN PHẨM--" }));
        cbMaDMSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaDMSPActionPerformed(evt);
            }
        });

        jLabel11.setText("Mã DMSP");

        cbTenSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "            --- TÊN SẢN PHẨM--" }));

        jLabel4.setText("Tên SP");

        jLabel5.setText("Đơn giá");

        jLabel6.setText("Giá bán");

        btrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btrefresh.setText("Làm mới");
        btrefresh.setOpaque(false);
        btrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrefreshActionPerformed(evt);
            }
        });

        btBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btBan.setText("Bán");
        btBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanActionPerformed(evt);
            }
        });

        jLabel3.setText("Tình trạng");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        jLabel7.setText("Tìm kiếm");

        btsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/timkiem.png"))); // NOI18N
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Picture.png"))); // NOI18N
        jLabel10.setText("Thông tin chi tiết sản phẩm");

        jLabel8.setText("Ngày bán");

        jLabel9.setText("Mã HĐ");

        jLabel12.setText("Số lượng");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1000, 500));
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tbbansanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "MaDM", "TenSP", "SoLuong", "Dongia", "Mã NPPSP", "Thoigiannhan", "Ghi Chú", "Tổng giá"
            }
        ));
        tbbansanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbansanphamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbbansanpham);

        jScrollPane3.setViewportView(jScrollPane2);

        jLabel14.setText("Tổng giá");

        txttonggia.setText("00");

        buttonGroup2.add(cethanhtoan);
        cethanhtoan.setText("Đã thanh toán");

        buttonGroup2.add(ceconno);
        ceconno.setText("Còn nợ");
        ceconno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceconnoActionPerformed(evt);
            }
        });

        jLabel16.setText("Tên SP");

        lbtongso.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lbtongso.setText("Tổng số");

        bthome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        bthome.setText("Home");
        bthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthomeActionPerformed(evt);
            }
        });

        cbNPPSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          ---NHÀ PP SẢN PHẨM-" }));

        jLabel13.setText("NPPSP");

        jLabel15.setText("Mã SP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bthome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cbMaDMSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(cbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cethanhtoan)
                                            .addGap(18, 18, 18)
                                            .addComponent(ceconno))
                                        .addComponent(datengayban, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(txtgiaban, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(txttonggia)
                                        .addComponent(txtmahoadon)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(64, 64, 64)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsearchtenSP)
                                    .addComponent(btsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(cbNPPSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btBan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btrefresh)
                                .addGap(137, 137, 137)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(lbtongso)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(bthome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBan)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbtongso)
                            .addComponent(btrefresh)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearchtenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbMaDMSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbNPPSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txttonggia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(datengayban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cethanhtoan)
                            .addComponent(ceconno)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMaDMSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaDMSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaDMSPActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    public void refresh(){
           
        this.txtsearchtenSP.setText(null);
        this.txtMaSP.setText(null);     
        this.cbMaDMSP.setSelectedItem(null);
        this.cbTenSP.setSelectedItem(null); 
        this.cbNPPSP.setSelectedItem(null);
        this.txtsoluong.setText(null);
        this.txtdongia.setText(null);
        this.txtgiaban.setText(null);
        this.txtmahoadon.setText(null);
        java.util.Date date = new java.util.Date();
        this.datengayban.setDate(date);
        
        this.txttonggia.setText("00");
        this.buttonGroup2.clearSelection();

       }
    private void btrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrefreshActionPerformed
        // làm mới sản phẩm
        this.btBan.setEnabled(false);
        refresh();
    }//GEN-LAST:event_btrefreshActionPerformed

    private void tbbansanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbansanphamMouseClicked
        // hiển thị dữ liệu lên text field
            
           int row = this.tbbansanpham.getSelectedRow();
           this.txtMaSP.setEnabled(false);
           this.cbMaDMSP.setEnabled(false);
           this.cbTenSP.setEnabled(false);
           this.cbNPPSP.setEnabled(false);
           this.txtdongia.setEnabled(false);
           this.btBan.setEnabled(true);
            try{
                if(row != -1 ){
                
                this.txtMaSP.setText(tbbansanpham.getValueAt(row,0).toString());
                this.cbMaDMSP.setSelectedItem(tbbansanpham.getValueAt(row,1).toString());
                this.cbTenSP.setSelectedItem(tbbansanpham.getValueAt(row,2).toString());
                this.cbNPPSP.setSelectedItem(tbbansanpham.getValueAt(row,5).toString());
                this.txtdongia.setText(tbbansanpham.getValueAt(row,4).toString());
                this.txtsoluong.setText(tbbansanpham.getValueAt(row,3).toString());
                
//                try
//                {       
//                        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tbbansanpham.getValueAt(row,8).toString());
//                        this.datengayban.setDate(date);
//                }
//                catch(Exception e)
//                {
//                    e.printStackTrace();
//                }                
                
//                this.txttonggia.setText(tbbansanpham.getValueAt(row, 9).toString());
                
//                String tinhtrang = this.tbbansanpham.getValueAt(row, row).toString();
                
//                switch (tinhtrang){
//                
//                    case "Da thanh toan":
//                        this.cethanhtoan.setSelected(true);
//                        this.ceconno.setSelected(false);
//                        break;
//                    case "Con No":
//                        this.ceconno.setSelected(true);
//                        this.cethanhtoan.setSelected(false);
//                        break;
//                    default:
//                        this.cethanhtoan.setSelected(true);
//                        this.ceconno.setSelected(true);
//                        break;
//                      
//                }
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbbansanphamMouseClicked
//    public void findTenSanPham(){
//        String tenSP = this.txtsearchtenSP.getText();
//        List<ThongTinSanPham> listSanPhams = null;
//        if(this.txtsearchtenSP.getText().length()==0){
//            JOptionPane.showMessageDialog(null, "Vui lòng nhập giá trị cần tìm kiếm !","Thông báo",2);
//            this.txtsearchtenSP.requestFocus();
//            return;
//        }
//        else{
//            
//            
//            listSanPhams = controllerBanSanPham.findTenSanPham(tenSP); 
//            
////            DefaultTableModel model = (DefaultTableModel)tbbansanpham.getModel();
//            model = new DefaultTableModel();
//            tbbansanpham.setModel(model);
//            loadDaTaSanPham();
////            tbbansanpham.getModel();
//
//               
//            
//             while(this.tbbansanpham.getRowCount()>0)
//             {
//                 tbbansanpham.remove(0);
//             }
//            this.tbbansanpham.getModel();
//              
//            this.lbtongso.setText("Có " +this.tbbansanpham.getRowCount()+ " Sản phẩm cần tìm ");
//            
//            
//        }
//    }
    
    public void findSanPham(String tenSP){
        
        String sql = "SELECT * FROM SANPHAMCONLAI where TenSP like ?";
        
        try
        {
            conn = connectDB.connectSQLServer();
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" +tenSP+ "%");
            rs = pst.executeQuery();
            
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
                SanPham sanPham = null;
            while(rs.next()){
                
                sanPham = new SanPham();
                
                    sanPham.setMaSP(rs.getString("MaSP"));
                    sanPham.setMaDM(rs.getString("MaDM"));
                    sanPham.setTenSP(rs.getString("TenSP"));
                    sanPham.setSoLuong(rs.getInt("SoLuong"));
                    sanPham.setDonGia(rs.getFloat("Dongia"));
                    sanPham.setMaNPPSP(rs.getString("MaNhaPPSS"));
                    sanPham.setThoiGianNhan(rs.getDate("Thoigiannhan"));
                    sanPham.setGhiChu(rs.getString("Ghichu"));
                    sanPham.setTongGia(rs.getFloat("Tonggia"));

                    
                    Vector row = new Vector();
                    row.add(sanPham.getMaSP());
                    row.add(sanPham.getMaDM());
                    row.add(sanPham.getTenSP());
                    row.add(sanPham.getSoLuong());
                    row.add(sanPham.getDonGia());
                    row.add(sanPham.getMaNPPSP());
                    row.add(sanPham.getThoiGianNhan());
                    row.add(sanPham.getGhiChu());
                    row.add(sanPham.getTongGia());


                model.addRow(row);
                 
            }
            this.tbbansanpham.setModel(model);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error: " +e.getMessage());
        }
    }
    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        // Tìm kiếm theo tên sản phẩm
        
        if(this.txtsearchtenSP.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập giá trị cần tìm kiếm !","Thông báo",2);
            this.txtsearchtenSP.requestFocus();
            return;
        }
        else{
            findSanPham(this.txtsearchtenSP.getText());
            this.lbtongso.setText("Có " +this.tbbansanpham.getRowCount()+ " Sản phẩm cần tìm ");
        }
 
    }//GEN-LAST:event_btsearchActionPerformed

    private void bthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthomeActionPerformed
        // quay tro lai man hinh luc dau chua tim kiem       
      loadDaTaSanPham();
      refresh();
    }//GEN-LAST:event_bthomeActionPerformed

    private void btBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanActionPerformed
        // Bán sản phẩm đang có
        if(this.txtmahoadon.getText().length()==0){
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập mã hóa đơn !","Thông báo",2);
                    this.txtmahoadon.requestFocus();
                    return;
        }
        if (this.txtsoluong.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng sản phẩm muốn bán","Thông báo",2);
                    this.txtsoluong.requestFocus();
                    return;
        }
        
        Pattern pattern = Pattern.compile("^[0-9]*$");
        Matcher matcher = pattern.matcher(this.txtsoluong.getText());
        if (!matcher.matches()) {
                    JOptionPane.showMessageDialog(null, "kí tự tại mục số lượng không phải là số!","Thông báo",2);
                    this.txtsoluong.requestFocus();
                    return;
        }
        if (this.txtgiaban.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Giá bán không được để trống","Thông báo",2);
                    this.txtgiaban.requestFocus();
                    return;
        }
        
        Pattern pattern1 = Pattern.compile("^[0-9]*$");
        Matcher matcher1 = pattern1.matcher(this.txtgiaban.getText());
        if (!matcher1.matches()) {
                    JOptionPane.showMessageDialog(null, "kí tự tại mục giá bán không phải là số!","Thông báo",2);
                    this.txtgiaban.requestFocus();
                    return;
        }

        if (this.txttonggia.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Tổng giá bán không được để trống","Thông báo",2);
                    this.txttonggia.requestFocus();
                    return;
        }
         
        Pattern pattern2 = Pattern.compile("^[0-9]*$");
        Matcher matcher2 = pattern2.matcher(this.txttonggia.getText());
        if (!matcher2.matches()) {
                    JOptionPane.showMessageDialog(null, "kí tự tại mục tổng giá không phải là số!","Thông báo",2);
                    this.txttonggia.requestFocus();
                    return;
        }
        if(this.cethanhtoan.isSelected()==false && this.ceconno.isSelected()==false){
                    JOptionPane.showMessageDialog(null,"Mời bạn chọn tình trạng thanh toán !","Thông báo",2);
                    this.cethanhtoan.requestFocus();
                    return;
        }
                
        
        BanSanPham sp = new BanSanPham();
        
        sp.setMaSP(this.txtMaSP.getText());
        sp.setMaDM((String) this.cbMaDMSP.getSelectedItem());
        sp.setTenSP((String) this.cbTenSP.getSelectedItem());  
        sp.setNPPSP((String) this.cbNPPSP.getSelectedItem());
        sp.setDonGia(Float.parseFloat(this.txtdongia.getText()));
        sp.setMaHD(this.txtmahoadon.getText());
        
        sp.setSoLuong(Integer.parseInt(this.txtsoluong.getText()));
        
        sp.setGiaBan(Float.parseFloat(this.txtgiaban.getText()));
        
        String a = this.txtsoluong.getText();
        String b = this.txtgiaban.getText();
        String c = this.txttonggia.getText();
        
        int a1 = Integer.parseInt(a);
        int b1 = Integer.parseInt(b);
        int c1 = Integer.parseInt(c);
        
        c1 = a1 * b1;
        
        String c2 = Integer.toString(c1);
        
        sp.setTongGia(Float.parseFloat(c2));
         
        sp.setNgayBan(this.datengayban.getDate());
  
        String tinhtrang = null;
        if(this.cethanhtoan.isSelected()){
            tinhtrang = "Da thanh toan";
        }
        if(this.ceconno.isSelected()){
            tinhtrang = "Con No";
        }   
        sp.setTinhTrang(tinhtrang);
        
        String maSP = this.txtMaSP.getText();
        boolean kq =  controllerBanSanPham.addDoanhThu(sp,maSP);
//        boolean kq1 = controllerBanSanPham.deleteSanPhamBanDuoc(this.txtMaSP.getText());
        if(kq){
            JOptionPane.showMessageDialog(null, "Đã bán sản phẩm !","Thông báo",1);
            DefaultTableModel model = (DefaultTableModel)tbbansanpham.getModel();
            model.setRowCount(0);
            loadDaTaSanPham();
            refresh();
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Thất bại","Thông báo",2);
        }
    }//GEN-LAST:event_btBanActionPerformed

    private void ceconnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceconnoActionPerformed
        // cong no khach hang
        
        frmBangcongnoKH frmcongnokh = new frmBangcongnoKH();
        frmcongnokh.setVisible(true);
    }//GEN-LAST:event_ceconnoActionPerformed
    public void checkSoLuong(String maSP){
                
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmbansanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmbansanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmbansanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmbansanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmbansanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBan;
    private javax.swing.JButton bthome;
    private javax.swing.JButton btrefresh;
    private javax.swing.JButton btsearch;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbMaDMSP;
    private javax.swing.JComboBox<String> cbNPPSP;
    private javax.swing.JComboBox<String> cbTenSP;
    private javax.swing.JCheckBox ceconno;
    private javax.swing.JCheckBox cethanhtoan;
    private com.toedter.calendar.JDateChooser datengayban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbtongso;
    private javax.swing.JTable tbbansanpham;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtsearchtenSP;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttonggia;
    // End of variables declaration//GEN-END:variables
}
