/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gym.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frmgiaodienchinh extends javax.swing.JFrame {

    /**
     * Creates new form frmgiaodienchinh
     */
    public frmgiaodienchinh() {
        initComponents();
        this.lbwellcom.setText(frmLogin.manv);
    }
    
    public void setVisibleAdmin(){
    
        this.menuhethong.setVisible(true);
        this.menudanhmuc.setVisible(true);
        this.menuquanly.setVisible(true);
        this.menuthongke.setVisible(true);
        this.menuabout.setVisible(true);
        this.menuluongnhanvien.setVisible(true);
        this.menuthongkekhachhang.setVisible(true);
        this.butkhachhang.setVisible(true);
        this.butnhanvien.setVisible(true);
        this.butsanpham.setVisible(true);
        this.butthongke.setVisible(true);
        this.butthongtin.setVisible(true);
        this.buttimkiem.setVisible(true);
        this.butdangxuat.setVisible(true);
    }

    
    public void setVisibleLeTan(){
        
        this.menunguoidung.setVisible(false);
        this.menuthongke.setVisible(false);
        this.butnhanvien.setEnabled(false);
        this.butthongke.setEnabled(false);
        

    }
    
    public void setVisiblePT(){
        
        this.menunguoidung.setVisible(false);
        this.menuquanlysanpham.setVisible(false);
        this.menusanpham.setVisible(false);
        this.menuthongke.setVisible(false);
        this.butnhanvien.setEnabled(false);
        this.butthongke.setEnabled(false);
        this.butsanpham.setEnabled(false);
        
    }
    
    public void setVisibleLaoCong(){
        
        this.menuhethong.setVisible(false);
        this.menudanhmuc.setVisible(false);
        this.menuquanly.setVisible(false);
        this.menuthongke.setVisible(false);
        this.menutrogiup.setVisible(false);
        this.butkhachhang.setVisible(false);
        this.butnhanvien.setVisible(false);
        this.butsanpham.setVisible(false);
        this.butthongke.setVisible(false);
        this.butthongtin.setVisible(false);
        this.buttimkiem.setVisible(false);
        this.butdangxuat.setVisible(false);
        this.menuthongke.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butkhachhang = new javax.swing.JButton();
        butsanpham = new javax.swing.JButton();
        butnhanvien = new javax.swing.JButton();
        butthongke = new javax.swing.JButton();
        butdangxuat = new javax.swing.JButton();
        butthongtin = new javax.swing.JButton();
        buttimkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbwellcom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuhethong = new javax.swing.JMenu();
        menudangxuat = new javax.swing.JMenuItem();
        menuexit = new javax.swing.JMenuItem();
        menudanhmuc = new javax.swing.JMenu();
        menumatkhau = new javax.swing.JMenuItem();
        menusanpham = new javax.swing.JMenuItem();
        menuquanly = new javax.swing.JMenu();
        menunguoidung = new javax.swing.JMenuItem();
        menukhachhang = new javax.swing.JMenuItem();
        menuquanlysanpham = new javax.swing.JMenuItem();
        menuthietbi = new javax.swing.JMenuItem();
        menuthongke = new javax.swing.JMenu();
        menudoanhthusanpham = new javax.swing.JMenuItem();
        menuthongkekhachhang = new javax.swing.JMenu();
        menudoanhthukhachhang = new javax.swing.JMenuItem();
        menuquanlycongno = new javax.swing.JMenuItem();
        menuluongnhanvien = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menutrogiup = new javax.swing.JMenu();
        menuabout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý phòng gym");
        setLocation(new java.awt.Point(200, 20));
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(960, 637));
        setResizable(false);
        getContentPane().setLayout(null);

        butkhachhang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butkhachhang.setForeground(new java.awt.Color(255, 51, 0));
        butkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/khachhang.png"))); // NOI18N
        butkhachhang.setText("Khách hàng");
        butkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butkhachhangActionPerformed(evt);
            }
        });
        getContentPane().add(butkhachhang);
        butkhachhang.setBounds(0, 50, 150, 50);

        butsanpham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butsanpham.setForeground(new java.awt.Color(255, 51, 0));
        butsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sanpham.png"))); // NOI18N
        butsanpham.setText("Sản phẩm");
        butsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsanphamActionPerformed(evt);
            }
        });
        getContentPane().add(butsanpham);
        butsanpham.setBounds(0, 290, 150, 50);

        butnhanvien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butnhanvien.setForeground(new java.awt.Color(255, 51, 0));
        butnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile.png"))); // NOI18N
        butnhanvien.setText("Nhân viên");
        butnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnhanvienActionPerformed(evt);
            }
        });
        getContentPane().add(butnhanvien);
        butnhanvien.setBounds(0, 210, 150, 50);

        butthongke.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butthongke.setForeground(new java.awt.Color(255, 51, 0));
        butthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thongke.png"))); // NOI18N
        butthongke.setText("Thống kê");
        butthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthongkeActionPerformed(evt);
            }
        });
        getContentPane().add(butthongke);
        butthongke.setBounds(0, 370, 150, 50);

        butdangxuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butdangxuat.setForeground(new java.awt.Color(255, 51, 0));
        butdangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/out.png"))); // NOI18N
        butdangxuat.setText("Đăng xuất");
        butdangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdangxuatActionPerformed(evt);
            }
        });
        getContentPane().add(butdangxuat);
        butdangxuat.setBounds(0, 537, 150, 50);

        butthongtin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butthongtin.setForeground(new java.awt.Color(255, 51, 0));
        butthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thongtin.png"))); // NOI18N
        butthongtin.setText("Trợ giúp");
        butthongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthongtinActionPerformed(evt);
            }
        });
        getContentPane().add(butthongtin);
        butthongtin.setBounds(0, 450, 150, 50);

        buttimkiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttimkiem.setForeground(new java.awt.Color(255, 51, 0));
        buttimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/password.png"))); // NOI18N
        buttimkiem.setText("Mật khẩu");
        buttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttimkiemActionPerformed(evt);
            }
        });
        getContentPane().add(buttimkiem);
        buttimkiem.setBounds(0, 130, 150, 50);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Xin chào:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 20, 90, 30);

        lbwellcom.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        lbwellcom.setForeground(new java.awt.Color(255, 0, 0));
        lbwellcom.setText("Tài khoản");
        getContentPane().add(lbwellcom);
        lbwellcom.setBounds(700, 20, 200, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hinhdaidien.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 590);

        menuhethong.setText("Hệ thống");

        menudangxuat.setText("Đăng xuất");
        menudangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudangxuatActionPerformed(evt);
            }
        });
        menuhethong.add(menudangxuat);

        menuexit.setText("Exit");
        menuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitActionPerformed(evt);
            }
        });
        menuhethong.add(menuexit);

        jMenuBar2.add(menuhethong);

        menudanhmuc.setText("Danh mục");

        menumatkhau.setText("Đổi mật khẩu");
        menumatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menumatkhauActionPerformed(evt);
            }
        });
        menudanhmuc.add(menumatkhau);

        menusanpham.setText("Bán sản phẩm");
        menusanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusanphamActionPerformed(evt);
            }
        });
        menudanhmuc.add(menusanpham);

        jMenuBar2.add(menudanhmuc);

        menuquanly.setText("Quản lý");

        menunguoidung.setText("Quản lý người dùng");
        menunguoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunguoidungActionPerformed(evt);
            }
        });
        menuquanly.add(menunguoidung);

        menukhachhang.setText("Quản lý khách hàng");
        menukhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menukhachhangActionPerformed(evt);
            }
        });
        menuquanly.add(menukhachhang);

        menuquanlysanpham.setText("Quản lý sản phẩm");
        menuquanlysanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuquanlysanphamActionPerformed(evt);
            }
        });
        menuquanly.add(menuquanlysanpham);

        menuthietbi.setText("Quản lý thiết bị tập");
        menuthietbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuthietbiActionPerformed(evt);
            }
        });
        menuquanly.add(menuthietbi);

        jMenuBar2.add(menuquanly);

        menuthongke.setText("Thống kê");

        menudoanhthusanpham.setText("Doanh thu sản phẩm");
        menudoanhthusanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudoanhthusanphamActionPerformed(evt);
            }
        });
        menuthongke.add(menudoanhthusanpham);

        menuthongkekhachhang.setText("Thống kê khách hàng");

        menudoanhthukhachhang.setText("Doanh thu khách hàng");
        menudoanhthukhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudoanhthukhachhangActionPerformed(evt);
            }
        });
        menuthongkekhachhang.add(menudoanhthukhachhang);

        menuquanlycongno.setText("Công nợ khách hàng");
        menuquanlycongno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuquanlycongnoActionPerformed(evt);
            }
        });
        menuthongkekhachhang.add(menuquanlycongno);

        menuthongke.add(menuthongkekhachhang);

        menuluongnhanvien.setText("Lương nhân viên");

        jMenuItem2.setText("Trả lương nhân viên");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuluongnhanvien.add(jMenuItem2);

        jMenuItem3.setText("Bảng lương nhân viên");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuluongnhanvien.add(jMenuItem3);

        menuthongke.add(menuluongnhanvien);

        jMenuBar2.add(menuthongke);

        menutrogiup.setText("Trợ giúp");

        menuabout.setText("About");
        menuabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaboutActionPerformed(evt);
            }
        });
        menutrogiup.add(menuabout);

        jMenuBar2.add(menutrogiup);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuthietbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuthietbiActionPerformed
        // TODO add your handling code here:
        frmquanlythietbitap frmthietbi = new frmquanlythietbitap();
        frmthietbi.setVisible(true);
    }//GEN-LAST:event_menuthietbiActionPerformed

    private void menumatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menumatkhauActionPerformed
        // TODO add your handling code here:
        frmdoimatkhau frmmatkhau = new frmdoimatkhau();
        frmmatkhau.setLocationRelativeTo(null);
        frmmatkhau.setVisible(true);
    }//GEN-LAST:event_menumatkhauActionPerformed

    private void menuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitActionPerformed
        // Exit liền không trả về trang chủ đăng nhập
       int confirmquit = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình không","Thông báo",JOptionPane.YES_NO_OPTION);
        if(confirmquit==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }   
    }//GEN-LAST:event_menuexitActionPerformed

    private void menunguoidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunguoidungActionPerformed
        // TODO add your handling code here:
        frmquanlynguoidung frmnguoidung = new frmquanlynguoidung();
        frmnguoidung.setVisible(true);
    }//GEN-LAST:event_menunguoidungActionPerformed

    private void menukhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menukhachhangActionPerformed
        // TODO add your handling code here:
        frmquanlykhachhang frmkhachhang = new frmquanlykhachhang();
        frmkhachhang.setVisible(true);
    }//GEN-LAST:event_menukhachhangActionPerformed

    private void menuquanlysanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuquanlysanphamActionPerformed
        // TODO add your handling code here:
        frmquanlysanpham frmsanpham = new frmquanlysanpham();
        frmsanpham.setVisible(true);
    }//GEN-LAST:event_menuquanlysanphamActionPerformed

    private void butkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butkhachhangActionPerformed
        // TODO add your handling code here:
        frmquanlykhachhang frmkhachhang = new frmquanlykhachhang();
        frmkhachhang.setVisible(true);
        
        
    }//GEN-LAST:event_butkhachhangActionPerformed

    private void menudoanhthusanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudoanhthusanphamActionPerformed
        // TODO add your handling code here:
        frmdoanhthusanpham frmdoanhthusanpham = new frmdoanhthusanpham();
        frmdoanhthusanpham.setVisible(true);
    }//GEN-LAST:event_menudoanhthusanphamActionPerformed

    private void menudoanhthukhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudoanhthukhachhangActionPerformed
        // TODO add your handling code here:
        frmdoanhthukhachhang frmdoanhthukhachhang = new frmdoanhthukhachhang();
        frmdoanhthukhachhang.setVisible(true);
    }//GEN-LAST:event_menudoanhthukhachhangActionPerformed

    private void menusanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusanphamActionPerformed
        // TODO add your handling code here:
        frmbansanpham frmbansanpham = new frmbansanpham();
        frmbansanpham.setVisible(true);
    }//GEN-LAST:event_menusanphamActionPerformed

    private void menuaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaboutActionPerformed
        // TODO add your handling code here:
        frmabout frmabout = new frmabout();
        frmabout.setVisible(true);
    }//GEN-LAST:event_menuaboutActionPerformed

    private void butsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsanphamActionPerformed
        // TODO add your handling code here:
        frmbansanpham frmbansanpham = new frmbansanpham();
        frmbansanpham.setVisible(true);
    }//GEN-LAST:event_butsanphamActionPerformed

    private void butnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnhanvienActionPerformed
        // TODO add your handling code here:
        frmquanlynguoidung frmnguoidung = new frmquanlynguoidung();
        frmnguoidung.setVisible(true);
    }//GEN-LAST:event_butnhanvienActionPerformed

    private void butthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthongkeActionPerformed
        // TODO add your handling code here:
        frmdoanhthukhachhang frmdoanhthukhachhang = new frmdoanhthukhachhang();
        frmdoanhthukhachhang.setVisible(true);
    }//GEN-LAST:event_butthongkeActionPerformed

    private void butthongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthongtinActionPerformed
        // TODO add your handling code here:
        frmabout frmthongtin   = new frmabout();
        frmthongtin.setVisible(true);
    }//GEN-LAST:event_butthongtinActionPerformed

    private void butdangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdangxuatActionPerformed
        // Đăng xuất khỏi hệ thống
        setVisibleLogin();
        dispose();
    }//GEN-LAST:event_butdangxuatActionPerformed

    private void menudangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudangxuatActionPerformed
        // Đăng xuất có trả về mục login
        setVisibleLogin();
        dispose();
    }//GEN-LAST:event_menudangxuatActionPerformed

    private void buttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttimkiemActionPerformed
        // TODO add your handling code here:
        frmdoimatkhau frmmatkhau = new frmdoimatkhau();
        frmmatkhau.setVisible(true);
    }//GEN-LAST:event_buttimkiemActionPerformed

    private void menuquanlycongnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuquanlycongnoActionPerformed
        // quản lý công nợ khách hàng
        
        frmBangcongnoKH frmcongnokhachhang = new frmBangcongnoKH();
        frmcongnokhachhang.setVisible(true);
    }//GEN-LAST:event_menuquanlycongnoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // trả lương nhân viên
        frmluongnhanvien  frmluongnhanvien = new frmluongnhanvien();
        frmluongnhanvien.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // bảng lương nhân viên
        frmBangLNV frmbangluongnv = new frmBangLNV();
        frmbangluongnv.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    public void setVisibleLogin(){
        
        int confirmdangxuat = JOptionPane.showConfirmDialog(null, "Bạn có muốn trở về trang Login không ? ","Thông báo",JOptionPane.YES_NO_OPTION);
        if(confirmdangxuat==JOptionPane.YES_NO_OPTION){
            frmLogin frmLogin1 = new frmLogin();
            frmLogin1.setVisible(true);
            dispose();
        }
        else{
            frmgiaodienchinh frmgiaodienchinh = new frmgiaodienchinh();
            frmgiaodienchinh.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmgiaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmgiaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmgiaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmgiaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmgiaodienchinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butdangxuat;
    private javax.swing.JButton butkhachhang;
    private javax.swing.JButton butnhanvien;
    private javax.swing.JButton butsanpham;
    private javax.swing.JButton butthongke;
    private javax.swing.JButton butthongtin;
    private javax.swing.JButton buttimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lbwellcom;
    private javax.swing.JMenuItem menuabout;
    private javax.swing.JMenuItem menudangxuat;
    private javax.swing.JMenu menudanhmuc;
    private javax.swing.JMenuItem menudoanhthukhachhang;
    private javax.swing.JMenuItem menudoanhthusanpham;
    private javax.swing.JMenuItem menuexit;
    private javax.swing.JMenu menuhethong;
    private javax.swing.JMenuItem menukhachhang;
    private javax.swing.JMenu menuluongnhanvien;
    private javax.swing.JMenuItem menumatkhau;
    private javax.swing.JMenuItem menunguoidung;
    private javax.swing.JMenu menuquanly;
    private javax.swing.JMenuItem menuquanlycongno;
    private javax.swing.JMenuItem menuquanlysanpham;
    private javax.swing.JMenuItem menusanpham;
    private javax.swing.JMenuItem menuthietbi;
    private javax.swing.JMenu menuthongke;
    private javax.swing.JMenu menuthongkekhachhang;
    private javax.swing.JMenu menutrogiup;
    // End of variables declaration//GEN-END:variables
}
