/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gym.View;

import Gym.Controller.ControllerCheckLog;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import Controller.connectDB;

/**
 *
 * @author Admin
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.lbconnect.setText(ControllerCheckLog.testConnect());
        this.getRootPane().setDefaultButton(jbutdangnhap);
    }
    
    public static ResultSet rs = null;
    public static PreparedStatement pst = null;
    public static Connection conn = null;
    public static Statement stt = null;
    public static String manv;
 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdangnhap = new javax.swing.JTextField();
        jbutnhaplai = new javax.swing.JButton();
        jbutexit = new javax.swing.JButton();
        txtmatkhau = new javax.swing.JPasswordField();
        jbutdangnhap = new javax.swing.JButton();
        lbconnect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập hệ thống");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(480, 170));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ĐĂNG NHẬP HỆ THỐNG");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile.png"))); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.png"))); // NOI18N
        jLabel3.setText("Mật khẩu");

        jbutnhaplai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reset.png"))); // NOI18N
        jbutnhaplai.setText("Nhập lại");
        jbutnhaplai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutnhaplaiActionPerformed(evt);
            }
        });

        jbutexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        jbutexit.setMnemonic('C');
        jbutexit.setText("Thoát");
        jbutexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutexitActionPerformed(evt);
            }
        });

        jbutdangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lock.png"))); // NOI18N
        jbutdangnhap.setMnemonic('L');
        jbutdangnhap.setText("Đăng nhập");
        jbutdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutdangnhapActionPerformed(evt);
            }
        });

        lbconnect.setText("Tình trạng kết nối");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txtmatkhau))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbconnect)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbutdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbutnhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jbutexit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutnhaplai)
                    .addComponent(jbutexit)
                    .addComponent(jbutdangnhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lbconnect)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutnhaplaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutnhaplaiActionPerformed
       
        this.txtdangnhap.setText(null);
        this.txtmatkhau.setText(null);
    }//GEN-LAST:event_jbutnhaplaiActionPerformed

    private void jbutdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutdangnhapActionPerformed
       if(this.txtdangnhap.getText().length()==0 || String.valueOf(this.txtmatkhau.getPassword()).length()==0)
       {
           JOptionPane.showMessageDialog(this,"Bạn chưa nhập thông tin tài khoản hoặc mật khẩu","Thông báo",2);
       }
       else
       {
           String sql = "SELECT *from NHANVIEN where TenTK = ? and Matkhau = ?";

           try
           {
               conn = connectDB.connectSQLServer();
               pst = conn.prepareStatement(sql);
               pst.setString(1, this.txtdangnhap.getText());
               pst.setString(2, String.valueOf(this.txtmatkhau.getPassword()));
               rs = pst.executeQuery();
               if(rs.next()){
                        
                   manv = this.txtdangnhap.getText();
                   String sqlquery = "SELECT * FROM NHANVIEN where ChucVu = ?";
                   pst = conn.prepareStatement(sqlquery);      
                   String checkChucVu = rs.getString("ChucVu");
                   String checkUser = rs.getString("TenTK");
                   String checkPass = rs.getString("Matkhau");
                   
                   pst.setString(1,checkChucVu);
                   rs = pst.executeQuery();
                   if(rs.next()){
                   
                        JOptionPane.showMessageDialog(this, " Xin chào " + this.txtdangnhap.getText(),"Thông báo",1);
                        frmgiaodienchinh frmgiaodien = new frmgiaodienchinh();
                        this.setVisible(false);  
                        frmgiaodien.setVisible(true);                
                        if(checkUser.equals(this.txtdangnhap.getText()) && checkPass.equals(String.valueOf(this.txtmatkhau.getPassword())) && checkChucVu.equals("Admin"))
                  {   
                      
                        frmgiaodien.setVisibleAdmin();
                  }
                  if(checkUser.equals(this.txtdangnhap.getText()) && checkPass.equals(String.valueOf(this.txtmatkhau.getPassword())) && checkChucVu.equals("Le Tan")){
                      
                        frmgiaodien.setVisibleLeTan();
                  }
                  if(checkUser.equals(this.txtdangnhap.getText()) && checkPass.equals(String.valueOf(this.txtmatkhau.getPassword())) && checkChucVu.equals("PT")){
                      
                        frmgiaodien.setVisiblePT();
                        
                     }
                  if(checkUser.equals(this.txtdangnhap.getText()) && checkPass.equals(String.valueOf(this.txtmatkhau.getPassword())) && checkChucVu.equals("Lao cong")){
                      
                        frmgiaodien.setVisibleLaoCong();
                        
                     }
                  }
                   
               }
               else
               {
                    JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại","Thông báo",0);
               }
               
           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null,e,"Thông báo",1);
           }
               
       }
    }//GEN-LAST:event_jbutdangnhapActionPerformed

    private void jbutexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutexitActionPerformed

             int confirmquit = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (confirmquit == JOptionPane.YES_NO_OPTION) {
                    System.exit(0);
                }
    }//GEN-LAST:event_jbutexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbutdangnhap;
    private javax.swing.JButton jbutexit;
    private javax.swing.JButton jbutnhaplai;
    private javax.swing.JLabel lbconnect;
    private javax.swing.JTextField txtdangnhap;
    private javax.swing.JPasswordField txtmatkhau;
    // End of variables declaration//GEN-END:variables
}
