/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gym.View;

import Gym.Controller.ControllerNhanVien;
import Gym.Model.NhanVien;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import Controller.connectDB;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class frmquanlynguoidung extends javax.swing.JFrame {

    /**
     * Creates new form frmquanlynguoidung
     */
    
    //ControllerNhanVien ctr; nghĩa là khởi tạo biến ctr có kiểu trả về là Đối tượng ControllerNhanVien
    //ControllerNhanVien ctr = new ControllerNhanVien là khởi tạo đối tượng ctr từ ControllerNhanVien
    //String[] headers = {"MaNV","Họ Tên","Ngày Sinh","Giới Tính","Số Điện Thoại","Địa Chỉ","Email","Tên TK","Chức Vụ"};
    //String[] chucVu = new String[]{"Admin","Lễ tân","PT","Lao công"};
    
    ControllerNhanVien controllerNhanVien = new ControllerNhanVien();
    DefaultTableModel model;
    public static PreparedStatement pst = null;
    public static Connection conn = null;
    public static ResultSet rs = null;
    
   
    public frmquanlynguoidung() {
        initComponents();
        setLocationRelativeTo(null);
        loadCBNhanVien();
        ShowCT();
        ProcessAction(false);
    }
    public void loadDaTaNhanVien(){
        model = new DefaultTableModel();
        //set colum cho title - headers
        Vector colum = new Vector();
        colum.add("MaNV");
        colum.add("Họ Tên");
        colum.add("Ngày Sinh");
        colum.add("Giới Tính");
        colum.add("Số Điện Thoại");
        colum.add("Địa Chỉ");
        colum.add("Email");
        colum.add("Ngày Vào Làm");
        colum.add("Tên TK");
        colum.add("Chức Vụ");
        //add colum headers vao model
        model.setColumnIdentifiers(colum);
        
        // set coumn cho data hien thi tren table
        List<NhanVien> listNhanVien = controllerNhanVien.getNhanVienFromDB();
        for(int i=0;i<listNhanVien.size(); i++){
            
            NhanVien nhanVien = (NhanVien)listNhanVien.get(i);
            Vector row = new Vector();
            row.add(nhanVien.getMaNV());
            row.add(nhanVien.getHoTen());
            row.add(nhanVien.getNgaySinh());
            row.add(checkGioiTinh(nhanVien.isGioiTinh()));
            row.add(nhanVien.getSoDienThoai());
            row.add(nhanVien.getDiaChi());
            row.add(nhanVien.getEmail());
            row.add(nhanVien.getNgayVaolam());
            row.add(nhanVien.getTenTK());
            row.add(nhanVien.getChucVu());
            //add row data vao model
            model.addRow(row);        
        }
        //set model cho table
        this.tbnhanvien.setModel(model);
 
    }
    
    // check gioi tinh nhan vien
    public String checkGioiTinh(boolean gioitinh){
        if(gioitinh==true){
            return "Nam";
        }
        else
        {
            return "Nu";
        }
    }
    public void loadCBNhanVien(){
        
//        for(String item: chucVu){
//            
//            this.cbchucvu.addItem(item.toString());
//        }
//        
        ArrayList<String> listCB = controllerNhanVien.loadCBNhanVien();
        for(String item: listCB){
            this.cbchucvu.addItem(item.toString());
        }
//        this.cbchucvu.removeAllItems();xóa tất cả item
    }
    
    public void ShowCT(){
        loadDaTaNhanVien();
        this.lbtongso.setText("Tổng số có "+this.tbnhanvien.getRowCount()+" nhân viên");
    }
    
    public void ProcessAction(boolean a){
        //cau lenh nay dung de dong bang cac button khi khong can thiet
         this.btAdd.setEnabled(a);
         this.btXoa.setEnabled(a);
         this.btSua.setEnabled(a);
           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jbutlammoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txthotennv = new javax.swing.JTextField();
        txtsodienthoai = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttentk = new javax.swing.JTextField();
        txtmk = new javax.swing.JTextField();
        cbchucvu = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txtmnv = new javax.swing.JTextField();
        lbtongso = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnhanvien = new javax.swing.JTable();
        datengaysinh = new com.toedter.calendar.JDateChooser();
        jlabel121 = new javax.swing.JLabel();
        datengayvaolam = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tạo tài khoản mới");
        setLocation(new java.awt.Point(250, 50));
        setMaximizedBounds(new java.awt.Rectangle(30, 10, 1300, 670));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ NGƯỜI DÙNG");

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btAdd.setText("Thêm mới");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        jbutlammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jbutlammoi.setText("Làm mới");
        jbutlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutlammoiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/info.png"))); // NOI18N
        jLabel2.setText("Thông tin chi tiết cá nhân");

        jLabel3.setText("Họ và tên");

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Số điện thoại");

        jLabel6.setText("Địa chỉ hiện nay");

        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        jLabel8.setText("Thông tin tài khoản");

        jLabel9.setText("Tên tài khoản");

        jLabel10.setText("Mật khẩu");

        jLabel12.setText("Chức vụ");

        jLabel14.setText("Giới tính");

        txtsodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsodienthoaiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/danhsach.png"))); // NOI18N
        jLabel13.setText("Danh sách người dùng");

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        buttonGroup1.add(rdNam);
        rdNam.setText("Nam");

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");

        jLabel15.setText("Mã nhân viên");

        lbtongso.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lbtongso.setText("Tổng số nhân viên");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 600));

        tbnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNV", "Họ tên", "Ngày sinh", "Giới tính", "SĐT", "Địa chỉ", "Email", "Ngày BĐ", "Tên NV", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbnhanvien);

        jScrollPane2.setViewportView(jScrollPane1);

        jlabel121.setText("Ngày Bắt Đầu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(btXoa)
                                .addGap(18, 18, 18)
                                .addComponent(jbutlammoi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(lbtongso))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jlabel121))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(22, 22, 22)
                                                        .addComponent(txtmk))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addComponent(cbchucvu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(22, 22, 22)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(datengayvaolam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                            .addComponent(txttentk)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel15))
                                                .addGap(13, 13, 13)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtsodienthoai, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                    .addComponent(txthotennv)
                                                    .addComponent(txtmnv, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                    .addComponent(txtdiachi, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                    .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                    .addComponent(datengaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(71, 71, 71)
                                                .addComponent(rdNam)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdNu)))))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSua)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutlammoi)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtongso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtmnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txthotennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(datengaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(rdNam)
                            .addComponent(rdNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel121)
                            .addComponent(datengayvaolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txttentk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cbchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsodienthoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsodienthoaiActionPerformed

    private void tbnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnhanvienMouseClicked
       // thiet lap gia tri cho bang khi click vao
        ProcessAction(true);
        this.btAdd.setEnabled(false);
        this.txtmnv.setEnabled(false);
           int row = this.tbnhanvien.getSelectedRow();
//           TableModel model = this.tbkhachhang.getModel();
//            if(row<0)
//                return;
//               
            try{
                if(row != -1 ){
                this.txtmnv.setText(tbnhanvien.getValueAt(row,0).toString());
                this.txthotennv.setText(tbnhanvien.getValueAt(row,1).toString());
                
                try
                {       
                        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tbnhanvien.getValueAt(row,2).toString());
                        this.datengaysinh.setDate(date);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                
                String gioitinh = this.tbnhanvien.getValueAt(row, 3).toString();
                if(gioitinh.equals("true") || gioitinh.equals("Nam")){
                
                    this.rdNam.setSelected(true);
                    this.rdNu.setSelected(false);
                }else{
                    this.rdNam.setSelected(false);
                    this.rdNu.setSelected(true);
                }
                this.txtsodienthoai.setText(tbnhanvien.getValueAt(row,4).toString());
                this.txtdiachi.setText(tbnhanvien.getValueAt(row,5).toString());
                this.txtemail.setText(tbnhanvien.getValueAt(row,6).toString());
                
                 try
                {       
                        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tbnhanvien.getValueAt(row,7).toString());
                        this.datengayvaolam.setDate(date);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                 
                this.txttentk.setText(tbnhanvien.getValueAt(row, 8).toString());
                this.cbchucvu.setSelectedItem(tbnhanvien.getValueAt(row,9).toString());

        }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbnhanvienMouseClicked

      public void refresh(){
           
        this.txtmnv.setText("");
        this.txthotennv.setText("");
        
        java.util.Date date = new java.util.Date();
        this.datengaysinh.setDate(date);
        
        this.buttonGroup1.clearSelection();
        this.txtsodienthoai.setText("");
        this.txtdiachi.setText("");
        this.txtemail.setText("");

        this.datengayvaolam.setDate(date);
        this.txtmk.setText("");
        this.txttentk.setText("");
        this.buttonGroup1.clearSelection();
        
        this.cbchucvu.setSelectedItem(null);

       }

    private void jbutlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutlammoiActionPerformed
       
        ProcessAction(false);
        this.btAdd.setEnabled(true);
        this.txtmnv.setEnabled(true);
        refresh();
        
    }//GEN-LAST:event_jbutlammoiActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // thêm mới nhân viên
        
        if(this.txtmnv.getText().length()==0){
                    JOptionPane.showMessageDialog(null,"Mã nhân viên không thể bỏ trống","Thông báo",2);
                    this.txtmnv.requestFocus();
                    return;
        }
        
        if(this.txtmnv.getText().length()>10){
                    JOptionPane.showMessageDialog(null,"Mã nhân viên không vượt quá 10 ký tự","Thông báo",2);
                    this.txtmnv.requestFocus();
                    return;
        }
        
        if (this.txthotennv.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Mời bạn nhập họ tên nhân viên","Thông báo",2);
                    this.txthotennv.requestFocus();
                    return;
        }
        
        if(this.rdNam.isSelected()==false && this.rdNu.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Mời bạn chọn giới tính","Thông báo",2);
                    this.rdNam.requestFocus();
                    return;
        }
        
        Pattern pattern = Pattern.compile("^[0-9]*$");
        Matcher matcher = pattern.matcher(this.txtsodienthoai.getText());
        if (!matcher.matches()) {
                    JOptionPane.showMessageDialog(null, "Số điện thoại vừa nhập không phải là số!");
                    this.txtsodienthoai.requestFocus();
                    return;
        }
        
        if(this.txtsodienthoai.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Số điện thoại không được bỏ trống","Thông báo",2);
                this.txtsodienthoai.requestFocus();
                return;
        }
        
        if(this.txtsodienthoai.getText().length()>15)
        {
                JOptionPane.showMessageDialog(null,"Số điện thoại vượt quá kí tự cho phép","Thông báo",2);
                this.txtsodienthoai.requestFocus();
                return;
        }
        
        if(this.txtdiachi.getText().length()==0){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập địa chỉ","Thông báo",2);
                this.txtdiachi.requestFocus();
                return;
        }
        
        if(this.txtemail.getText().length()==0){
                JOptionPane.showMessageDialog(null,"Mời bạn nhập email","Thông báo",2);
                this.txtemail.requestFocus();
                return;
        }
        
        String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        if (!this.txtemail.getText().matches(EMAIL_REGEX)) {
                    JOptionPane.showMessageDialog(null, "Mời bạn nhập email chính xác");
                    this.txtemail.requestFocus();
                    return;
        }
        
        if(this.txttentk.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Tên tài khoản không được bỏ trống","Thông báo",2);
                    this.txttentk.requestFocus();
                    return;
        }
        
        if(this.txtmk.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Vui lòng nhập mật khẩu","Thông báo",2);
                    this.txtmk.requestFocus();
                    return;
        }
        
        if(this.txtmk.getText().length()<5)
        {
            JOptionPane.showMessageDialog(null,"Mật khẩu nhập quá ngắn","Thông báo",2);
                    this.txtmk.requestFocus();
                    return;
        }
        
        if(this.cbchucvu.getSelectedItem()==null)
            {
                JOptionPane.showMessageDialog(null,"Vui lòng chọn chức vụ","Thông báo",2);
                this.cbchucvu.requestFocus();
                return;
            }
        
        NhanVien nv = new NhanVien();
        
        nv.setMaNV(this.txtmnv.getText());
        nv.setHoTen(this.txthotennv.getText());
        nv.setNgaySinh(this.datengaysinh.getDate());
        
        boolean gioitinh = this.rdNam.isSelected();
        
        if(gioitinh){
            this.rdNam.isSelected();
        }else{
            this.rdNu.isSelected();
        }
        
        nv.setGioiTinh(gioitinh);
        
        nv.setSoDienThoai(Integer.parseInt(this.txtsodienthoai.getText()));
        nv.setDiaChi(this.txtdiachi.getText());
        nv.setEmail(this.txtemail.getText());
        
        nv.setNgayVaolam(this.datengayvaolam.getDate());
        nv.setTenTK(this.txttentk.getText());
        nv.setMatKhau(this.txtmk.getText());
        nv.setChucVu((String) this.cbchucvu.getSelectedItem());
        
        boolean kq =  controllerNhanVien.addNewNhanVien(nv);
        if(kq){
            JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công","Thông báo",1);
            DefaultTableModel model = (DefaultTableModel)tbnhanvien.getModel();
            model.setRowCount(0);
            loadDaTaNhanVien();
            ProcessAction(false);
            refresh();
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Thêm thất bại","Thông báo",2);
        }

    }//GEN-LAST:event_btAddActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        //Edit nhân viên
        
        if(this.txtmnv.getText().length()==0){
                    JOptionPane.showMessageDialog(null,"Mã nhân viên không thể bỏ trống","Thông báo",2);
                    this.txtmnv.requestFocus();
                    return;
        }
        if(this.txtmnv.getText().length()>10){
                    JOptionPane.showMessageDialog(null,"Mã nhân viên không vượt quá 10 ký tự","Thông báo",2);
                    this.txtmnv.requestFocus();
                    return;
        }
        if (this.txthotennv.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Mời bạn nhập họ tên nhân viên","Thông báo",2);
                    this.txthotennv.requestFocus();
                    return;
        }
        if(this.rdNam.isSelected()==false && this.rdNu.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Mời bạn chọn giới tính","Thông báo",2);
                    this.rdNam.requestFocus();
                    return;
        }
        
        Pattern pattern = Pattern.compile("^[0-9]*$");
        Matcher matcher = pattern.matcher(this.txtsodienthoai.getText());
        if (!matcher.matches()) {
                    JOptionPane.showMessageDialog(null, "Số điện thoại vừa nhập không phải là số!");
                    this.txtsodienthoai.requestFocus();
                    return;
        }
        if(this.txtsodienthoai.getText().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Số điện thoại không được bỏ trống","Thông báo",2);
                this.txtsodienthoai.requestFocus();
                return;
        }
        if(this.txtsodienthoai.getText().length()>15)
        {
                JOptionPane.showMessageDialog(null,"Số điện thoại vượt quá kí tự cho phép","Thông báo",2);
                this.txtsodienthoai.requestFocus();
                return;
        }
        if(this.txtdiachi.getText().length()==0){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập địa chỉ","Thông báo",2);
                this.txtdiachi.requestFocus();
                return;
        }
        if(this.txtemail.getText().length()==0){
                JOptionPane.showMessageDialog(null,"Mời bạn nhập email","Thông báo",2);
                this.txtemail.requestFocus();
                return;
        }
        String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        if (!this.txtemail.getText().matches(EMAIL_REGEX)) {
                    JOptionPane.showMessageDialog(null, "Mời bạn nhập email chính xác");
                    this.txtemail.requestFocus();
                    return;
        }
        if(this.txttentk.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Tên tài khoản không được bỏ trống","Thông báo",2);
                    this.txttentk.requestFocus();
                    return;
        }
        if(this.txtmk.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Vui lòng nhập mật khẩu","Thông báo",2);
                    this.txtmk.requestFocus();
                    return;
        }
        if(this.txtmk.getText().length()<5)
        {
            JOptionPane.showMessageDialog(null,"Mật khẩu nhập quá ngắn","Thông báo",2);
                    this.txtmk.requestFocus();
                    return;
        }
        if(this.cbchucvu.getSelectedItem()==null)
            {
                JOptionPane.showMessageDialog(null,"Vui lòng chọn chức vụ","Thông báo",2);
                this.cbchucvu.requestFocus();
                return;
            }
        
        NhanVien nv = new NhanVien();
        
        nv.setMaNV(this.txtmnv.getText());
        nv.setHoTen(this.txthotennv.getText());
        nv.setNgaySinh(this.datengaysinh.getDate());
        
        boolean gioitinh = this.rdNam.isSelected();
        
        if(gioitinh){
            this.rdNam.isSelected();
        }else{
            this.rdNu.isSelected();
        }
        
        nv.setGioiTinh(gioitinh);
        
        nv.setSoDienThoai(Integer.parseInt(this.txtsodienthoai.getText()));
        nv.setDiaChi(this.txtdiachi.getText());
        nv.setEmail(this.txtemail.getText());
        
        nv.setNgayVaolam(this.datengayvaolam.getDate());
        nv.setTenTK(this.txttentk.getText());
        nv.setMatKhau(this.txtmk.getText());
        nv.setChucVu((String) this.cbchucvu.getSelectedItem());
        
        boolean kq =  controllerNhanVien.upDateNhanVien(nv);
        if(kq){
            JOptionPane.showMessageDialog(null, "Sửa nhân viên thành công","Thông báo",1);
            DefaultTableModel model = (DefaultTableModel)tbnhanvien.getModel();
            model.setRowCount(0);
            loadDaTaNhanVien();
            ProcessAction(false);
            refresh();
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Sửa thất bại","Thông báo",2);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // Xóa nhân viên
        
        if(this.txtmnv.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Bạn cần chọn mã khách hàng để xóa","Thông báo",2);
        else
        {   
            int confirmdelete = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa mã nhân viên này không ?"," Thông báo ",JOptionPane.YES_NO_OPTION);
            if (confirmdelete == JOptionPane.YES_NO_OPTION){
                boolean kq = controllerNhanVien.deleteNhanVien(this.txtmnv.getText());
                if(kq){
                    JOptionPane.showMessageDialog(null,"Bạn đã xóa thành công","Thông báo",1);
                    DefaultTableModel model = (DefaultTableModel)tbnhanvien.getModel();
                    model.setRowCount(0);
                    loadDaTaNhanVien();
                    ProcessAction(false);
                    refresh();
                }else{
                    JOptionPane.showMessageDialog(null,"Xóa thất bại !","Thông báo",2);
                }
            }        
        }
    }//GEN-LAST:event_btXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmquanlynguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmquanlynguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmquanlynguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmquanlynguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmquanlynguoidung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbchucvu;
    private com.toedter.calendar.JDateChooser datengaysinh;
    private com.toedter.calendar.JDateChooser datengayvaolam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbutlammoi;
    private javax.swing.JLabel jlabel121;
    private javax.swing.JLabel lbtongso;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbnhanvien;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthotennv;
    private javax.swing.JTextField txtmk;
    private javax.swing.JTextField txtmnv;
    private javax.swing.JTextField txtsodienthoai;
    private javax.swing.JTextField txttentk;
    // End of variables declaration//GEN-END:variables


}
