/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gym.View;

import Gym.Controller.Controllerthietbi;
import Gym.Model.ThietBi;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.Vector;

import Gym.Model.ThongTinThietBi;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class frmquanlythietbitap extends javax.swing.JFrame {

    /**
     * Creates new form frmthietbitap
     */
    
    Controllerthietbi controllerthietbi;
    ThietBi thietBi;
    public static PreparedStatement pst = null;
    public static Connection conn= null;
    public static ResultSet rs = null;
    DefaultTableModel model;
    
    public frmquanlythietbitap() {
        initComponents();
        loadDaTaThietBi();
        ProcessAction(false);
        loadCBDMTB();
        loadCBNPPTB();
    }
    
    public void loadDaTaThietBi(){
        model = new DefaultTableModel();
        
        Vector colum = new Vector();
        
        colum.add("Mã TB");
        colum.add("Mã DM");
        colum.add("Tên DM");
        colum.add("Tên TB");
        colum.add("Số Lượng");
        colum.add("Giá Cả");
        colum.add("Tổng Giá");
        colum.add("Tình Trạng");
        colum.add("Mã NPP");
        colum.add("Tên NPP");
        colum.add("Mô Tả");
        
        model.setColumnIdentifiers(colum);
        
        //set colum cho data hiển thị trên table
        controllerthietbi = new Controllerthietbi();
        List<ThongTinThietBi> listThietBi = controllerthietbi.getDataThietBi();
        for(int i = 0;i<listThietBi.size(); i++){
            
            ThongTinThietBi thietBi = (ThongTinThietBi)listThietBi.get(i);
            
            Vector row = new Vector();
            row.add(thietBi.getMaThietBi());
            row.add(thietBi.getMaDMTB());
            row.add(thietBi.getTenDMTB());
            row.add(thietBi.getTenThietBi());
            row.add(thietBi.getSoLuong());
            row.add(thietBi.getDonGia());
            row.add(thietBi.getTongGia());
            row.add(thietBi.getTinhTrang());
            row.add(thietBi.getMaNhaPP());
            row.add(thietBi.getTenNPPTB());
            row.add(thietBi.getMoTa());
            
            model.addRow(row);
        }
        //set table cho model.
        this.tbthietbi.setModel(model);
    }
    public String checkTinhTrang(boolean tinhtrang){
        if(tinhtrang==true){
            return "Tot";
        }else{
            return "Bi Loi";
        }
    }
    
    public void ProcessAction(boolean a){
    
         this.btadd.setEnabled(a);
         this.btdelete.setEnabled(a);
         this.btedit.setEnabled(a);
    }
    
    public void loadCBDMTB(){
               
        ArrayList<String> listCBDMTB = controllerthietbi.loadCBDMTB();
        for(String item: listCBDMTB){
            this.cbDMTB.addItem(item.toString());
        }
    }
    public void loadCBNPPTB(){
               
        ArrayList<String> listCBNPPTB = controllerthietbi.LoadCBNPPTB();
        for(String item: listCBNPPTB){
            this.cbNPP.addItem(item.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btadd = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btrefresh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbDMTB = new javax.swing.JComboBox<>();
        txttenTB = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        txtdongia = new javax.swing.JTextField();
        cbNPP = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmota = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbthietbi = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbhinhanh = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        cebtot = new javax.swing.JCheckBox();
        cebloi = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtMaTB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txttongia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý thiết bị tập");
        setLocation(new java.awt.Point(50, 10));
        setMaximizedBounds(new java.awt.Rectangle(30, 10, 1300, 670));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("QUẢN LÝ THIẾT BỊ TẬP");

        jLabel2.setText("Danh mục TB");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/info.png"))); // NOI18N
        jLabel3.setText("Thông tin chi tiết");

        btadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btadd.setText("Thêm");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        btedit.setText("Sửa");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btdelete.setText("Xóa");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        btrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btrefresh.setText("Làm mới");
        btrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrefreshActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên thiết bị");

        jLabel5.setText("Số lượng");

        jLabel6.setText("Đơng giá");

        jLabel7.setText("Tình trạng");

        jLabel8.setText("Nhà phân phối");

        jLabel10.setText("Mô tả");

        cbDMTB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ---MÃ DANH MỤC THIẾT BỊ--" }));

        cbNPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "     ---MÃ NHÀ PHÂN PHỐI---" }));

        txtmota.setColumns(20);
        txtmota.setRows(5);
        jScrollPane2.setViewportView(txtmota);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1000, 402));

        tbthietbi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thiết bị", "Mã DM Thiết bị", "Tên DM thiết bị", "Tên thiết bị", "Số lượng", "Giá cả", "Tổng giá", "Tình trạng", "Mã NPPTB", "Nhà PPTB", "Mô tả"
            }
        ));
        tbthietbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbthietbiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbthietbi);

        jScrollPane4.setViewportView(jScrollPane3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Picture.png"))); // NOI18N
        jLabel11.setText("BẢNG CHI TIẾT THIẾT BỊ");

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        lbhinhanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton5.setText("Hình ảnh");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TB01", "Thiết bị tập tay"},
                {"TB02", "Thiết bị tập ngực"},
                {"TB03", "Thiết bị tập chân"},
                {"TB04", "Thiết bị tập bụng"}
            },
            new String [] {
                "Mã DM thiết bị", "Tên DM thiết bị"
            }
        ));
        jTable2.setRowHeight(25);
        jScrollPane1.setViewportView(jTable2);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setText("DANH MỤC THIẾT BỊ");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NPPTB01", "Công ty thiết bị vật tư phòng gym 365", "20 Ngô Quyền - Đà Nẵng"},
                {"NPPTB02", "Công ty thiết bị sport whey TKT", "30 Lê Hữu Trác - TP.HCM"},
                {"NPPTB03", "Tổng đại lý phân phối Impusle tại Việt Nam", "120 Lê Duẩn - Hà Nội"},
                {"NPPTB04", "Hệ Thống phân phối thiết bị gym NK - SPORT", "550 Từ Liên - Hà Nội"}
            },
            new String [] {
                "Mã NPPTB", "Tên NPPTB", "Địa chỉ NPPTB"
            }
        ));
        jTable3.setRowHeight(25);
        jScrollPane5.setViewportView(jTable3);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel13.setText("DANH MỤC NHÀ PHÂN PHỐI THIẾT BỊ");

        buttonGroup1.add(cebtot);
        cebtot.setText("HĐ Tốt");

        buttonGroup1.add(cebloi);
        cebloi.setText("Bị lỗi");

        jLabel14.setText("Mã thiết bị");

        jLabel15.setText("Tổng giá");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btedit)
                        .addGap(18, 18, 18)
                        .addComponent(btdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btrefresh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)))
                                    .addComponent(jButton5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdongia)
                                    .addComponent(txtsoluong)
                                    .addComponent(txttenTB)
                                    .addComponent(cbDMTB, 0, 186, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(cbNPP, 0, 186, Short.MAX_VALUE)
                                    .addComponent(lbhinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(cebtot)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cebloi)
                                        .addGap(27, 27, 27))
                                    .addComponent(txtMaTB)
                                    .addComponent(txttongia))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btadd)
                    .addComponent(btedit)
                    .addComponent(btdelete)
                    .addComponent(btrefresh))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(txtMaTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbDMTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(txttenTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(cebloi))
                                    .addComponent(jLabel11)
                                    .addComponent(cebtot))))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbNPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(74, 74, 74)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbthietbiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbthietbiMouseClicked
        // show data len text field
        
        ProcessAction(true);
        this.btadd.setEnabled(false);
        this.txtMaTB.setEnabled(false);
           int row = this.tbthietbi.getSelectedRow();
              
            try{
                if(row != -1 ){
                this.txtMaTB.setText(tbthietbi.getValueAt(row,0).toString());
                
                this.cbDMTB.setSelectedItem(tbthietbi.getValueAt(row,1).toString());
                this.txttenTB.setText(tbthietbi.getValueAt(row,3).toString());
                this.txtsoluong.setText(tbthietbi.getValueAt(row,4).toString());
                this.txtdongia.setText(tbthietbi.getValueAt(row,5).toString());
                this.txttongia.setText(tbthietbi.getValueAt(row,6).toString());
                
                String tinhTrang = this.tbthietbi.getValueAt(row, 7).toString();
//                có thể sử dụng switch case hoặc là if else để dùng
                switch (tinhTrang){
                    case "Tot":
                        this.cebtot.setSelected(true);
                        this.cebloi.setSelected(false);
                        break;
                    case "Bi loi":
                        this.cebloi.setSelected(true);
                        this.cebtot.setSelected(false);  
                        break;
                    default:
                        this.cebtot.setSelected(true);
                        this.cebloi.setSelected(true);
                        break;
                }
                
                //khai bao bien kieu bit true false thi lam cach duoi
//                if(tinhTrang.equals("true") || tinhTrang.equals("Tot")){
//                
//                    this.cebtot.setSelected(true);
//                    this.cebloi.setSelected(false);
//                }else{
//                    this.cebtot.setSelected(false);
//                    this.cebloi.setSelected(true);
//                } 
                this.cbNPP.setSelectedItem(tbthietbi.getValueAt(row, 8).toString());
                this.txtmota.setText(tbthietbi.getValueAt(row,10).toString());
              
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbthietbiMouseClicked

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // add new thiết bị tập
        
        if(this.txtMaTB.getText().length()==0){
                    JOptionPane.showMessageDialog(null,"Mã thiết bị  không thể bỏ trống","Thông báo",2);
                    this.txtMaTB.requestFocus();
                    return;
        }
        if(this.cbDMTB.getSelectedItem()==null)
        {
                JOptionPane.showMessageDialog(null,"Vui lòng chọn danh mục thiết bị","Thông báo",2);
                this.cbDMTB.requestFocus();
                return;
        }
        if(this.txttenTB.getText().length()==0){
                    JOptionPane.showMessageDialog(null,"Tên thiết bị không thể bỏ trống","Thông báo",2);
                    this.txttenTB.requestFocus();
                    return;
        }
        if (this.txtsoluong.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng !","Thông báo",2);
                    this.txtsoluong.requestFocus();
                    return;
        }
        if (this.txtdongia.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập đơn giá!","Thông báo",2);
                    this.txtdongia.requestFocus();
                    return;
        }
        if (this.txttongia.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập tổng giá!","Thông báo",2);
                    this.txttongia.requestFocus();
                    return;
        }
        if(this.cebtot.isSelected()==false && this.cebloi.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Mời bạn chọn tình trạng thiết bị !","Thông báo",2);
                    this.cebtot.requestFocus();
                    return;
        }
        
        if(this.cbNPP.getSelectedItem()==null)
        {
                JOptionPane.showMessageDialog(null,"Vui lòng chọn nhà phân phối","Thông báo",2);
                this.cbNPP.requestFocus();
                return;
        }      
        
        thietBi = new ThietBi();
        
        thietBi.setMaThietBi(this.txtMaTB.getText());
        thietBi.setMaDMTB((String) this.cbDMTB.getSelectedItem());
        thietBi.setTenThietBi(this.txttenTB.getText());
        thietBi.setSoLuong(Integer.parseInt(this.txtsoluong.getText()));
        thietBi.setDonGia(Integer.parseInt(this.txttongia.getText()));
        thietBi.setTongGia(Integer.parseInt(this.txttongia.getText()));
        
        String tinhtrang = null;
        if(this.cebtot.isSelected()){
            tinhtrang = "Tot";
        }
        if(this.cebloi.isSelected()){
            tinhtrang = "Bi loi";
        }   
        thietBi.setTinhTrang(tinhtrang);
        
        thietBi.setMaNhaPP((String) this.cbNPP.getSelectedItem());       
        thietBi.setMoTa(this.txtmota.getText());
        
        controllerthietbi = new Controllerthietbi();
        boolean kq =  controllerthietbi.addNewThietBi(thietBi);
        if(kq){
            JOptionPane.showMessageDialog(null, "Thêm thiết bị thành công","Thông báo",1);
            DefaultTableModel model = (DefaultTableModel)tbthietbi.getModel();
            model.setRowCount(0);
            loadDaTaThietBi();
            ProcessAction(false);
            refresh();
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Thêm thất bại","Thông báo",2);
        }
    }//GEN-LAST:event_btaddActionPerformed

     public void refresh(){
           
        this.txtMaTB.setText(null);   
        this.cbDMTB.setSelectedItem(null);      
        this.txttenTB.setText(null);
        this.txtsoluong.setText(null);
        this.txtdongia.setText(null);
        this.txttongia.setText(null);
        this.buttonGroup1.clearSelection();
        this.cbNPP.setSelectedItem(null);
        this.txtmota.setText(null);

       }
    private void btrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrefreshActionPerformed
        // làm mới
        
        refresh();
        ProcessAction(false);
        this.btadd.setEnabled(true);
        this.txtMaTB.setEnabled(true);
    }//GEN-LAST:event_btrefreshActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // edit thiet bi
        
        if(this.txtMaTB.getText().length()==0){
                    JOptionPane.showMessageDialog(null,"Mã thiết bị  không thể bỏ trống","Thông báo",2);
                    this.txtMaTB.requestFocus();
                    return;
        }
        if(this.cbDMTB.getSelectedItem()==null)
        {
                JOptionPane.showMessageDialog(null,"Vui lòng chọn danh mục thiết bị","Thông báo",2);
                this.cbDMTB.requestFocus();
                return;
        }
        if(this.txttenTB.getText().length()==0){
                    JOptionPane.showMessageDialog(null,"Tên thiết bị không thể bỏ trống","Thông báo",2);
                    this.txttenTB.requestFocus();
                    return;
        }
        if (this.txtsoluong.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng !","Thông báo",2);
                    this.txtsoluong.requestFocus();
                    return;
        }
        if (this.txtdongia.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập đơn giá!","Thông báo",2);
                    this.txtdongia.requestFocus();
                    return;
        }
        if (this.txttongia.getText().length()==0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập tổng giá!","Thông báo",2);
                    this.txttongia.requestFocus();
                    return;
        }
        if(this.cebtot.isSelected()==false && this.cebloi.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Mời bạn chọn tình trạng thiết bị !","Thông báo",2);
                    this.cebtot.requestFocus();
                    return;
        }
        
        if(this.cbNPP.getSelectedItem()==null)
        {
                JOptionPane.showMessageDialog(null,"Vui lòng chọn nhà phân phối","Thông báo",2);
                this.cbNPP.requestFocus();
                return;
        }      
        
        thietBi = new ThietBi();
        
        thietBi.setMaThietBi(this.txtMaTB.getText());
        thietBi.setMaDMTB((String) this.cbDMTB.getSelectedItem());
        thietBi.setTenThietBi(this.txttenTB.getText());
        thietBi.setSoLuong(Integer.parseInt(this.txtsoluong.getText()));
        thietBi.setDonGia(Integer.parseInt(this.txttongia.getText()));
        thietBi.setTongGia(Integer.parseInt(this.txttongia.getText()));
        
        String tinhtrang = null;
        if(this.cebtot.isSelected()){
            tinhtrang = "Tot";
        }
        if(this.cebloi.isSelected()){
            tinhtrang = "Bi loi";
        }   
        thietBi.setTinhTrang(tinhtrang);
        
        thietBi.setMaNhaPP((String) this.cbNPP.getSelectedItem());       
        thietBi.setMoTa(this.txtmota.getText());
        
        controllerthietbi = new Controllerthietbi();
        boolean kq =  controllerthietbi.upDateThietBi(thietBi);
        if(kq){
            JOptionPane.showMessageDialog(null, "Sửa thành công","Thông báo",1);
            DefaultTableModel model = (DefaultTableModel)tbthietbi.getModel();
            model.setRowCount(0);
            loadDaTaThietBi();
            ProcessAction(false);
            refresh();
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Sửa thất bại","Thông báo",2);
        }
    }//GEN-LAST:event_bteditActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // delete thiết bị
        
        if(this.txtMaTB.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Bạn cần chọn mã thiết bị để xóa !","Thông báo",2);
        }else{
            int confirmdelete = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa thiết bị này không ? ","Thông báo",JOptionPane.YES_NO_OPTION);
            if(confirmdelete == JOptionPane.YES_NO_OPTION){
                controllerthietbi = new Controllerthietbi();
                boolean kq = controllerthietbi.deleteThietBi(this.txtMaTB.getText());
                if(kq)
                {
                JOptionPane.showMessageDialog(null,"Bạn đã xóa thiết bị thành công !","Thông báo",1);
                DefaultTableModel model = (DefaultTableModel)tbthietbi.getModel();
                model.setRowCount(0);
                loadDaTaThietBi();
                ProcessAction(false);
                refresh();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Xóa thất bại !","Thông báo",2);
                }
            }         
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmquanlythietbitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmquanlythietbitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmquanlythietbitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmquanlythietbitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmquanlythietbitap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btrefresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDMTB;
    private javax.swing.JComboBox<String> cbNPP;
    private javax.swing.JCheckBox cebloi;
    private javax.swing.JCheckBox cebtot;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lbhinhanh;
    private javax.swing.JTable tbthietbi;
    private javax.swing.JTextField txtMaTB;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextArea txtmota;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenTB;
    private javax.swing.JTextField txttongia;
    // End of variables declaration//GEN-END:variables
}
